### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by jcubic** [xloem/emterm#1]
It would be nice to have demo online, you can use GitHub pages to host static files.

**Comment by xloem** [comment]
thanks for looking at this =)  i'm not really able to continue this project more at this time ...  i'm happy to help walk others through getting a demo going, though, if anybody wants to slowly move towards it.

**Comment by jcubic** [comment]
I'm trying to build it myself. But if the build it's working you only need to add test.html file and set GitHub pages in settings. It will be no more then the effort you did when replying to this issue. Take few minutes of time. But the ower of the repo have to do it.

**Comment by jcubic** [comment]
Ok, never mind this project don't even work, I can't type my name after build and run test.html file.

**Comment by xloem** [comment]
I'm the owner of the repo.  The project's designed for developers who can add the features they need or port its ideas upstream.  It probably needs some specific steps to make it work.

**Comment by jcubic** [comment]
You've link this repo in this issue, and it don't work. My hack work. If you don't want even show this is something that work then maybe you should delete you comment from emscripten-core/emscripten#6115 since this only make things confusing. You've linked your project as solution to the issue.

**Comment by xloem** [comment]
In the comment, I said "I started", _started_.  It is only a start.  Not a solution.

**Comment by xloem** [comment]
To clarify, also, I am interested in sharing a working demo.  I tried to make that clear earlier.  I have not made one yet, but if there's interest I can work through it with somebody.

**Comment by jcubic** [comment]
Oh, I'm sorry then I though it was working solution that can be used. I recently needed it again I found your comment and want try it out.

I don't think I would be able to help much I'm not very familiar with emscripten. I just wanted to glue few things together and make it working. Maybe I will dig deeper into Emscripten. I wanted to play with Gambit Scheme compiled to JS. Check this project https://feeley.github.io/gambit-in-the-browser/ it have working async read in terminal. The code is not open source but you can look at the code. 

If you decide to try the link and are not familar with scheme, type `(read)`  press enter then type something and press enter (try not to use spaces).

**Comment by jcubic** [comment]
Also just to let you know your project if it would work would probably got some users. If you can use it out of the box, just installed it side by side with emscipten and make it work. There are lot of projects that would would benefit. But it probably would require lot of work if you said that this is not working. But if xterm.js would be used as the front with this you would be able to compile editor written in C++ or C into JS and xterm.js that would be pretty awesome if would just work.

But it's probably log way if basic test don't work, did you made that test.html working on your machine?
